ci: Bump symfony/phpunit-bridge
If we try to install dependencies with `composer update --prefer-lowest`, then on PHP 8.4, `composer test` would fail with:

    Deprecated: PHPUnit\Framework\TestCase::run(): Implicitly marking parameter $result as nullable is deprecated, the explicit nullable type must be used instead in vendor/bin/.phpunit/phpunit-9.5-0/src/Framework/TestCase.php on line 754

    Fatal error: Trait "Symfony\Bridge\PhpUnit\Legacy\PolyfillAssertTrait" not found in vendor/bin/.phpunit/phpunit-9.5-0/src/Framework/Assert.php on line 91

These support PHP ≥ 7.2.5 and ≥ 8.1.0, respectively.